config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :create, :update]

    devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_image

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :books, dependent: :destroy

          has_one_attached :profile_image

          validates :name, length: { minimum: 2 }
          validates :name, length: { maximum: 20 }
          validates :name, uniqueness: true
          validates :introduction, length: { maximum: 50 }

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
   before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
      user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
      root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action:correct_user, only:[:edit, :update, :destroy]

def create
  @book = Book.new(book_params)
  @book.user_id = current_user.id
  if @book.save
    flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
   else
      @user = current_user
      @books = Book.all
      render :index
    end
end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
  end

  def edit
    #@newbook = Book.new
    #@user = User.find(params[:id])
    #@books = Book.all
    @user = current_user
    @book = Book.find(params[:id])
  end

def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
  else
    @user = current_user
    render :edit
  end
end

def destroy
  book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path  # 投稿一覧画面へリダイレクト
end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to books_path
  end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
    
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def guest_sign_in
        user = User.guest
        sign_in user
        redirect_to user_path(user), notice: 'guestuserでログインしました。'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action:correct_user, only:[:edit, :update]
before_action :ensure_guest_user, only: [:edit]

  def show
    @newbook = Book.new
    #@book = Book.find(params[:id])

    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    #@newuser = User.new
    #@users = User.all
    @cuser = current_user
    @user = User.find(params[:id])

  end


  def index
    @book = Book.new
    
    @users = User.all
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)

    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)

    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


  def correct_user

    @user = User.find(params[:id])
    unless @user == current_user
    redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th><th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th><th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      
      <% if user.name != "guestuser" %>
      <div class='row'>
        <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
      </div>
      <% end %>
      
       

      

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">

  <div>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  </div>

<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    <%= form_with model:@book do |f| %>
    <div class="form-group">
      <label for="inputTitle">Title</label>

  <%= f.text_field :title, autofocus: true, id:"inputTitle", class: "form-control" %>

    </div>
    <div class="form-group">
      <label for="inputBody">Opinion</label>

  <%= f.text_field :body, autofocus: true, id:"inputBody", class: "form-control" %>

    </div>
    <div class="form-group">
       <%= f.submit "Update Book" %>
<% end %>

    </div>
    <%= link_to "Show", book_path(@book.id) %> |
    <%= link_to "Back", books_path %>
  </div>

</div>
</div>

app/views/books/index.html.erb
as

<div class="container px-5 px-sm-0">
<%= flash[:notice] %>
  <div>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  </div>

<%= render 'books', user: @user %>


<h2 class="mt-3">New book</h2>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
<div class="row">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>
          Title
        </th>
        <th>
          Opinion
        </th>
      </tr>
    </thead>
    <tbody>

<% @books.each do |book| %>
  <tr>

  <td>
    <%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %>
  </td>

<td><%= link_to book.title, book_path(book.id) %></td>
  <td><%= book.body %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
</div>
</div>


</div>
</div>

app/views/books/show.html.erb
<div class="container">


  <%= render 'books', user:@user %>


      <h2 class="mt-3">New book</h2>

<%= form_with model: @newbook do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>

    </div>



<div class="col-md-8 offset-md-1">
  <div class="row">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
            <%= image_tag @user.get_profile_image(100, 100) %><br>
            <%= @user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to @book.title %>
        </td>
        <td>
          <%= @book.body %>
        </td>

 <% if @book.user == current_user %>
<td>
 <%= link_to "Edit", edit_book_path(@book.id) %>


        </td>
        <td>
          <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

        </td>
        <% end %>
      </tr>

    </tbody>
  </table>
  </div>
</div>

</div>


</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
        <h1 class="px3 mx-auto">
            Welcome to 
            <strong><i class="fas fa-book"></i>Bookers</strong>
            !
        </h1>
    </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!</h1>
<p>In <strong><i class="fas fa-book fa-xs"></i>Bookers</strong>, </p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p> about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
  
  <div class="row">
    <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block md-3 sign_in", method: :post %>
  </div>
  
  <div class="row">
    <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn" %>
  </div>
  <div class="row">
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn" %>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
          <a class="navbar-brand" href="/">
              <span> Bookers </span>
          </a>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

         <li>


           <div class="social">
             <i class="fas fa-home"></i>
        <%= link_to "Home", user_path(current_user) %>

      </li>
      <li><i class="fas fa-users"></i>
        <%= link_to "Users", users_path %>
      </li>
      <li><i class="fas fa-book-open"></i>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <i class="fas fa-sign-out-alt"></i>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>

        </div>
              </li>
    <% else %>


            <li>
            <div class="social">
              <i class="fas fa-home"></i>
              <%= link_to "Home", root_path %>
            </li>
            <li><i class="fas fa-link"></i>
              <%= link_to "About", about_path %>
            </li>
            <li><i class="fas fa-user-plus"></i>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li><i class="fas fa-sign-in-alt"></i>
              <%= link_to "Log in", new_user_session_path %>
            </div>
            </li>
            <% end %>
          </ul>
        </div>
        </div>
        </nav>


  </header>
<%= flash[:notice] %>
     <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
          </div>
        </div>
</div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  
  <div>
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  </div>
  
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user do |f| %>
    <div class="form-group">
      <label for="name">Name</label>

  <%= f.text_field :name, autofocus: true, id:"name", class: "form-control" %>

    </div>
    <div class="form-group">
      <label for="profile_image">Image</label>
      <%= f.file_field :profile_image, placeholder: "profile_image", accept: "image/*", class: "form-control-file" %>
      </div>
    <div class="form-group">
      <label for="introduction">Introduction</label>

  　　<%= f.text_field :introduction, autofocus: true, id:"introduction", class: "form-control" %>

    </div>
    <div class="form-group">
       <%= f.submit "Update User", class: "btn btn-secondary" %>
    </div>
<% end %>



  </div>

</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/books', user:@user %>

  <h2 class="mt-3">New book</h2>

<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
<div class="row">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>
          name
        </th>
        <th>

        </th>
      </tr>
    </thead>
    <tbody>

<% @users.each do |user| %>
  <tr>
  <td>
    
    <%=  image_tag user.get_profile_image(100,100) %>
    
    </td>
<td><%= user.name %></td>
  <td><%= link_to "Show", user_path(user.id) %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
</div>
</div>


</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">

    <%= render 'books/books', user:@user %>

    <h2 class="mt-3">New book</h2>

<%= form_with model: @newbook do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>
</div>


<div class="col-md-8 offset-md-1">
  <div class="row">
  <h2>Books</h2>
  <table class="table">
      <thead>
          <tr>
              <th></th>
          <th>Title</th>
          <th>Opinion</th>
          </tr>
      </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
         <%= link_to user_path(book.user) do %>
<%= image_tag book.user.get_profile_image(100, 100) %>
         <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <td>

        </td>
      </tr>
<% end %>
    </tbody>
  </table>
  </div>
</div>

</div>


</div>